### ISSUE TITLE
After the installation stopped working paintshop

### ISSUE THREAD

**Issue by SAYREXx** [SPKcoding/A3_Epoch_ESVP#1]
Hi! After the installation stopped working paintshop....  
 The problem starts after adding a file description.ext  class:
class CfgNotifications {
             #include "SPKcode\ESVP\notifications.h"
};
 How can I fix it?

**Comment by SPKcoding** [comment]
The problem is, I can´t take a look into every available script. That is someone which should have get managed by the specific user itself. 
But as soon as Iam able to I will take a look into it, if it is still relevant. :)
